### ISSUE TITLE
README DOCUMENTATION , CONTIBUTING AND CODE OF CONDUCT FILE 

### ISSUE THREAD

**Issue by akrish4** [rituvermaCS/Eggy-Bowl#1]
Hi @rituvermaCS 
Since this a newly created repository and doesn't have much documentation , I would like to add contributing file , code of conduct file and update readme accordingly , you know readme files are which people see first to get better understanding of project 

I will be beautifying the whole readme with badges and emoji and make it attractive 

Kindly assign me this issue @rituvermaCS

**Comment by akrish4** [comment]
Hi @rituvermaCS 
Kindly do assign and add the labels to this issue

**Comment by Dhriti-Roy** [comment]
May I start working on it.

**Comment by akrish4** [comment]
Do one thing , Open similar kind of issue because I am not interested in working on it
