### ISSUE TITLE
CONTRIBUTING.md is misnamed

### ISSUE THREAD

**Issue by Akshu-on-github** [rituvermaCS/Eggy-Bowl#16]
**Describe the bug**

**Expected behaviour**
It should be CONTRIBUTING.md as per opensource guidelines

**Impact**
Most new-comers expect a `CONTRIBUTING.md`. Additionally, your insights page doesn't recognise it:
![image](https://user-images.githubusercontent.com/61582763/107116544-f97dfa80-6899-11eb-9a68-2e049092b358.png)
Thus, it might turn away some who wish to contribute

**Additional context**
It isn't a huge typo @rituvermaCS, but I'd like to work on this

**Comment by Akshu-on-github** [comment]
And I'm participating in the DWOC so I'd appreciate it if I could get a confirmation soon 😄

**Comment by rituvermaCS** [comment]
@Akshu-on-github go with it
