### ISSUE TITLE
Edit the last gif and Happy Coding to be center-aligned in Readme.md

### ISSUE THREAD

**Issue by vismitap** [rituvermaCS/Eggy-Bowl#24]
## 📚 Documentation

(A clear and concise description of what the issue is.)
Edit the last gif and Happy Coding to be center-aligned in Readme.md and make it perfect 😅
## Have you spent some time to check if this issue has been raised before?

(Have you googled for a similar issue or checked our older issues for a similar bug)
Yes

Please assign me this issue!

**Comment by vismitap** [comment]
Still not center-aligned but looks good this way as image size is increased! Dk in typora it shows center-aligned 😅🤔. You are okay with the edited version right?

**Comment by rituvermaCS** [comment]
yeah 👍🏼
