### ISSUE TITLE
Pr template creation

### ISSUE THREAD

**Issue by Sloth-Panda** [rituvermaCS/Eggy-Bowl#4]
Let me know if this needs to be done

**Comment by smriti1313** [comment]
Hi, I would like to work on this. Let me know if there's still a chance. Thank you.

**Comment by rituvermaCS** [comment]
> Hi, I would like to work on this. Let me know if there's still a chance. Thank you.

**Comment by rituvermaCS** [comment]
@smriti1313 and @Sloth-Panda I thought, It is done...Thankyou for showing your interest.
